"""Add created_at and updated_at fields to users table

Revision ID: 5e6f7a6dc31a
Revises: 162f5a158e81
Create Date: 2024-11-29 09:46:07.611990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6f7a6dc31a'
down_revision: Union[str, None] = '162f5a158e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
